version: '3'
services:
  # web:
  #   image: nginx:mailline-alpine
  #   restart: always
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   depends_on:
  #     - app

  app:
    image: 190ikp/django:latest
    restart: always
    # depends_on:
    #   - db
    ports:
      - '8000:8000'
    volumes:
      - ./back/src:/usr/src/app
    command: >
      /bin/sh -c
      "pip install --no-cache-dir -r requirements.txt
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

  # db:
  #   image: mysql:8.0
  #   restart: always
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     TZ: 'Asia/Tokyo'
  #     MYSQL_DATABASE: 'django'
  #     MYSQL_USER: 'django'
  #     MYSQL_PASSWORD: 'django'
  #     MYSQL_ROOT_PASSWORD: 'example'
  #   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci