# Generated by Django 2.2 on 2019-04-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('when_remind', models.IntegerField(choices=[(1, '15min before'), (2, '30min before'), (3, '1h before')])),
            ],
        ),
    ]
